apiVersion: v1
kind: ConfigMap
metadata:
  name: stackgres-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  values.json: |
    {{ toJson .Values | nindent 4 }}
